name: CI Angular app through GitHub Actions

on: 
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm@8.x

      - name: Setup
        run: pnpm install

      - name: Test
        run: |
          pnpm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: build angular, output in dist/cv_project
        run: | 
          CI=false pnpm run build
      - name: show dir
        run: |
          ls -la dist/cv_project/browser

      - name: Download, run httpd image, container name serving_base, map to port 8080
        run: | 
          docker run -d -p 8080:80 --name serving_base httpd
      - name: docker ps
        run: |
           docker ps
      - name: cp angular build to container
        run: | 
          docker cp dist/cv_project/browser/. serving_base:/usr/local/apache2/htdocs
         

      - name: list container
        run: | 
          docker exec serving_base ls -la /usr/local/apache2/htdocs
          
      - name: Build the custom Docker image
        run: |
            docker commit --change "ENV MODEL_NAME ${{secrets.MODEL_NAME}}" \
            --change "EXPOSE 8080" \
             serving_base ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}
            
      - name: show docker images
        run: docker images
        
      - name: docker login
        env: 
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: | 
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}

      - name: Verify the server is running
        run: |
          curl -I http://localhost:8080
          
  
        
    
        

