name: CI Angular app through GitHub Actions

on: 
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm@8.x

      - name: Setup
        run: pnpm install

      - name: Test
        run: |
          pnpm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: build angular, output in dist/cv_project
        run: | 
          CI=false pnpm run build
          
      - name: show dir 
        run: |
          ls -la dist      
