name: CI Angular app through GitHub Actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm@8.x

      - name: Setup
        run: pnpm install

      - name: Test
        run: |
          pnpm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build Angular, output in dist/cv_project
        run: |
          CI=false pnpm run build

      - name: Generate self-signed certificate
        run: |
          mkdir -p certs
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout certs/selfsigned.key -out certs/selfsigned.crt -subj "/CN=localhost"

      - name: List generated certificates
        run: ls -la certs

      - name: Download and run Nginx image, with HTTPS configuration
        run: |
          docker run -d -p 443:443 --name serving_base nginx

      - name: Copy Angular build and certificates to container
        run: |
          docker cp dist/cv_project/browser/. serving_base:/usr/share/nginx/html
          docker cp certs/selfsigned.crt serving_base:/etc/nginx/selfsigned.crt
          docker cp certs/selfsigned.key serving_base:/etc/nginx/selfsigned.key

      - name: Verify files in Nginx container
        run: |
          docker exec serving_base ls -la /etc/nginx/selfsigned.*

      - name: Create Nginx configuration file
        run: |
          echo "
          server {
              listen 443 ssl;
              ssl_certificate /etc/nginx/selfsigned.crt;
              ssl_certificate_key /etc/nginx/selfsigned.key;
              location / {
                  root /usr/share/nginx/html;
                  index index.html index.htm;
              }
          }" > nginx.conf

      - name: Copy Nginx configuration to container
        run: |
          docker cp nginx.conf serving_base:/etc/nginx/conf.d/default.conf

      - name: Wait for Nginx to start
        run: sleep 5

      - name: Reload Nginx
        run: docker exec serving_base nginx -s reload

      - name: List configuration and certificate files
        run: docker exec serving_base ls -la /etc/nginx /etc/nginx/conf.d

      - name: Show Nginx config
        run: docker exec serving_base cat /etc/nginx/conf.d/default.conf

      - name: Show Nginx error log
        run: docker exec serving_base cat /var/log/nginx/error.log

      - name: Verify HTTPS server
        run: curl -kI https://localhost
