name: CI Angular app through GitHub Actions

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install pnpm
        run: npm install -g pnpm@8.x

      - name: Setup
        run: pnpm install

      - name: Test
        run: |
          pnpm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: build angular, output in dist/cv_project
        run: |
          CI=false pnpm run build
      - name: show dir
        run: |
          ls -la dist/cv_project/browser

      - name: Generate self-signed certificate
        run: |
          mkdir -p certs
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -keyout certs/selfsigned.key -out certs/selfsigned.crt -subj "/CN=localhost"

      - name: Download and run Nginx image, with HTTPS configuration
        run: |
          docker run -d -p 443:443 --name serving_base nginx

      - name: Copy Angular build and certificates to container
        run: |
          docker cp dist/cv_project/browser/. serving_base:/usr/share/nginx/html
          docker cp certs/selfsigned.crt serving_base:/etc/nginx/selfsigned.crt
          docker cp certs/selfsigned.key serving_base:/etc/nginx/selfsigned.key

      - name: Configure HTTPS in Nginx
        run: |
          docker exec serving_base sh -c 'echo "
          server {
              listen 443 ssl;
              ssl_certificate /etc/nginx/selfsigned.crt;
              ssl_certificate_key /etc/nginx/selfsigned.key;
              location / {
                  root /usr/share/nginx/html;
                  index index.html index.htm;
              }
          }" > /etc/nginx/conf.d/default.conf'

      - name: List container contents
        run: docker exec serving_base ls -la /usr/share/nginx/html

      - name: Build the custom Docker image
        run: |
          docker commit --change "EXPOSE 443" serving_base ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}

      - name: Show docker images
        run: docker images

      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/${{secrets.MODEL_NAME}}:${{github.sha}}

      - name: Verify the server is running with HTTPS
        run: |
          curl -kI https://localhost
